# Generated by Django 5.0.7 on 2024-12-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0015_interest_skill_remove_userprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='name',
            field=models.CharField(choices=[('ai', 'Artificial Intelligence'), ('ml', 'Machine Learning'), ('data_science', 'Data Science'), ('web_development', 'Web Development'), ('mobile_development', 'Mobile Development'), ('cloud_computing', 'Cloud Computing'), ('cybersecurity', 'Cybersecurity'), ('blockchain', 'Blockchain'), ('software_engineering', 'Software Engineering'), ('iot', 'Internet of Things')], max_length=100),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('javascript', 'JavaScript'), ('html', 'HTML'), ('css', 'CSS'), ('django', 'Django'), ('react', 'React'), ('nodejs', 'Node.js'), ('sql', 'SQL'), ('git', 'Git')], max_length=100),
        ),
    ]
