# Generated by Django 5.0.7 on 2024-12-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0016_alter_interest_name_alter_skill_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='skills',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='interests',
            field=models.CharField(blank=True, choices=[('ai', 'Artificial Intelligence'), ('ml', 'Machine Learning'), ('data_science', 'Data Science'), ('web_development', 'Web Development'), ('mobile_development', 'Mobile Development'), ('cloud_computing', 'Cloud Computing'), ('cybersecurity', 'Cybersecurity'), ('blockchain', 'Blockchain'), ('software_engineering', 'Software Engineering'), ('iot', 'Internet of Things')], max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skills',
            field=models.CharField(blank=True, choices=[('python', 'Python'), ('java', 'Java'), ('javascript', 'JavaScript'), ('html', 'HTML'), ('css', 'CSS'), ('django', 'Django'), ('react', 'React'), ('nodejs', 'Node.js'), ('sql', 'SQL'), ('git', 'Git')], max_length=500, null=True),
        ),
    ]
