# Generated by Django 5.0.7 on 2024-12-27 10:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0020_alter_userprofile_bio_alter_userprofile_interests_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentorshiprequest',
            old_name='mentor',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='mentorshiprequest',
            old_name='mentee',
            new_name='sender',
        ),
        migrations.AddField(
            model_name='mentorshiprequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mentorshiprequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], default='Pending', max_length=10),
        ),
    ]
