# Generated by Django 5.0.7 on 2024-12-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0023_rename_sender_mentorshiprequest_mentee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorshiprequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10),
        ),
    ]
