# Generated by Django 5.0.7 on 2024-12-27 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0028_alter_mentorshiprequest_mentee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorshiprequest',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='mentorshiprequest',
            name='mentee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='homepage.userprofile'),
        ),
        migrations.AlterField(
            model_name='mentorshiprequest',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='homepage.userprofile'),
        ),
        migrations.AlterField(
            model_name='mentorshiprequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('denied', 'Denied')], max_length=10),
        ),
    ]
